/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== help.md ==================
static const unsigned char temp_binary_data_5[] =
"# AMidiOrgan User Guide\n"
"\n"
"For the complete end-user operations manual (including packaged Windows/macOS installation), open `USER_MANUAL.md` included in the release package (same folder level as the app package contents).\n"
"\n"
"## What This App Does\n"
"AMidiOrgan is a live-performance MIDI controller built with JUCE and C++.\n"
"It manages voice button groups across three keyboard panels, supports layering and split workflows,\n"
"and routes MIDI to connected hardware and software sound modules from a single interface.\n"
"\n"
"The three performance panels are:\n"
"\n"
"- `Upper`\n"
"- `Lower`\n"
"- `Bass&Drums`\n"
"\n"
"Each panel uses the active configuration and panel data to determine which voices, routing, effects,\n"
"presets, and rotary states are available during a performance.\n"
"\n"
"## Supported Modules (Current)\n"
"\n"
"- Deebach BlackBox\n"
"- Roland Integra7\n"
"- Ketron SD2\n"
"- MIDI GM\n"
"- Custom MIDI (JSON-based)\n"
"\n"
"Contact the developer for additional module support.\n"
"\n"
"## Startup Flow (Recommended)\n"
"\n"
"1. Open the `Start` tab.\n"
"2. Select MIDI input and output devices (selections are restored automatically on the next launch when the same ports are available).\n"
"3. Select the active sound module using `To Modules`.\n"
"4. Load a panel (`.pnl`) and config (`.cfg`) if needed.\n"
"5. Confirm the panel and config labels match what you expect.\n"
"6. Move to `Upper`, `Lower`, or `Bass&Drums` and start playing.\n"
"\n"
"## Tab Guide\n"
"\n"
"### Start\n"
"\n"
"- Lists MIDI input and output devices and updates as devices connect or disconnect.\n"
"- Lets you choose the active sound module.\n"
"- Loads panel and config files.\n"
"- Checks config/panel pairing when loading and can warn if the selected files do not belong together.\n"
"\n"
"### Upper / Lower / Bass&Drums\n"
"\n"
"- These are the main performance tabs.\n"
"- Each tab contains voice button groups, volume controls, mute, and preset recall.\n"
"- `Upper` and `Lower` also include rotary controls.\n"
"- `Save` and `Save As` write the current panel (`.pnl`) to disk.\n"
"- The preset buttons are shared across all three keyboard tabs.\n"
"\n"
"### Sounds\n"
"\n"
"- Assigns an instrument voice to the currently selected voice button.\n"
"- Select the target voice button on a keyboard tab before opening `Sounds`.\n"
"- Browse in two levels inside the `Sounds for Voice Button` area:\n"
"  - Level 1: voice category buttons\n"
"  - Level 2: voice buttons in the selected category\n"
"- Clicking a voice sends MSB/LSB/PC immediately on the button group's MIDI output channel for audition.\n"
"- `Back` returns to categories. `Prev` / `Next` paginate when lists exceed visible space.\n"
"- Use `To Upper`, `To Lower`, or `To Bass` to return to the performance tab.\n"
"\n"
"### Effects\n"
"\n"
"- Edits per-voice MIDI effect values in real time.\n"
"- Select the target voice button on a keyboard tab before opening `Effects`.\n"
"- Effect changes are applied on the button group's MIDI output channel as you edit them.\n"
"- Use `To Upper`, `To Lower`, or `To Bass` to return to the performance tab.\n"
"- Current effect set:\n"
"  - VOL\n"
"  - EXP\n"
"  - REV\n"
"  - CHO\n"
"  - MOD\n"
"  - TIM\n"
"  - ATK\n"
"  - REL\n"
"  - BRI\n"
"  - PAN\n"
"\n"
"### Config\n"
"\n"
"- Edits button group routing and behavior:\n"
"  - group name\n"
"  - MIDI In / Out channel\n"
"  - octave shift\n"
"  - solo split point for Upper / Lower\n"
"- `MIDI Reset` sends a controller reset on all 16 channels.\n"
"- `MIDI In Passthru` is a global input-channel filter, not a per-device or per-output setting.\n"
"- When it is **ON**, all incoming MIDI channels are allowed through.\n"
"- When it is **OFF**, only MIDI input channels assigned to button groups are allowed through; other incoming channels are blocked.\n"
"- MIDI channel `16` is still allowed for controller-style traffic even when pass-through is off.\n"
"- Config settings are global to the app and are separate from the currently loaded panel.\n"
"\n"
"### Hotkeys\n"
"\n"
"- Lets you assign keyboard shortcuts for tabs, presets, and rotary controls.\n"
"- Available values are `A-Z`, `0-9`, and `(None)`.\n"
"- `Save` applies the current shortcut map and writes it to disk.\n"
"- `Cancel` restores the last applied shortcut map.\n"
"- Duplicate non-empty shortcuts are blocked.\n"
"\n"
"### Help\n"
"\n"
"- Shows this guide.\n"
"\n"
"### Exit\n"
"\n"
"- Exits the application.\n"
"- If panel-related changes are pending, the app may ask whether you want to save before quitting.\n"
"\n"
"## Performance Behavior\n"
"\n"
"### Voice Button Groups\n"
"\n"
"- A voice button group is a logical set of related voice buttons.\n"
"- Each group uses routing and performance settings from the active config.\n"
"- Every group has a volume slider with Up / Down controls.\n"
"- Groups can be muted and unmuted during performance.\n"
"\n"
"### Mute and Layering\n"
"\n"
"- Muting is used for fast live layering control.\n"
"- When a group is muted, its volume slider and Up / Down controls are disabled.\n"
"- While muted, new MIDI Note On events are blocked for that group's output channel (hard mute).\n"
"- On mute, the app sends cleanup controllers to that output channel:\n"
"  - Sustain Off (`CC64=0`)\n"
"  - All Notes Off (`CC123=0`)\n"
"- Mute does not send `CC7=0`; channel volume is restored by the normal volume path on unmute.\n"
"\n"
"### Presets\n"
"\n"
"- There are 7 presets in total:\n"
"  - `Manual`\n"
"  - Presets `1` to `6`\n"
"- `Manual` is the default preset on startup.\n"
"- Each preset stores the active voice button in each button group across all three keyboard tabs.\n"
"- Each preset also stores per-button-group rotary snapshot values used during preset recall.\n"
"- Preset programming flow:\n"
"  1. Select the target preset.\n"
"  2. Adjust the active voice buttons as needed.\n"
"  3. Click `Preset Set`.\n"
"  4. Click the preset button again to write the snapshot.\n"
"- Save the panel if you want preset changes to persist to disk.\n"
"\n"
"### Rotary\n"
"\n"
"- Rotary controls are available on `Upper` and `Lower`.\n"
"- Rotary supports `Fast/Slow` and `Brake`.\n"
"- Switching between `Upper`, `Lower`, and `Bass&Drums` refreshes the rotary controls from saved manual state.\n"
"- Upper and Lower manual rotary states are saved with the panel.\n"
"- Presets also store per-group rotary values for recall.\n"
"\n"
"## Keyboard Shortcuts\n"
"\n"
"When the main window has focus, the default shortcuts are:\n"
"\n"
"| Action | Key |\n"
"|--------|-----|\n"
"| Upper tab | `A` |\n"
"| Lower tab | `S` |\n"
"| Bass tab | `D` |\n"
"| Sounds tab | `Z` |\n"
"| Effects tab | `X` |\n"
"| Manual preset | `0` |\n"
"| Preset 1 | `1` |\n"
"| Preset 2 | `2` |\n"
"| Preset 3 | `3` |\n"
"| Preset 4 | `4` |\n"
"| Preset 5 | `5` |\n"
"| Preset 6 | `6` |\n"
"| Upper rotary Fast/Slow | `F` |\n"
"| Upper rotary Brake | `B` |\n"
"| Lower rotary Fast/Slow | `G` |\n"
"| Lower rotary Brake | `N` |\n"
"\n"
"Shortcut notes:\n"
"\n"
"- Upper and Lower rotary shortcuts always target their respective manuals, even when another tab is selected.\n"
"- Sounds and Effects shortcuts are intended for use after a target voice button has been selected on a keyboard tab.\n"
"- While a `TextEditor`, `ComboBox`, or modal dialog has keyboard focus, global shortcuts are deferred so normal typing continues to work.\n"
"- Some plain controls may still allow letter shortcuts when they have focus.\n"
"\n"
"### Customizing Shortcuts\n"
"\n"
"- Open the `Hotkeys` tab to edit shortcuts.\n"
"- `Save` writes the current map to:\n"
"  - `Documents/AMidiOrgan/configs/hotkeys.json`\n"
"- That file is loaded on startup when it is present.\n"
"- If the file is missing, the app uses the built-in defaults shown above.\n"
"\n"
"## Saving, Loading, and File Locations\n"
"\n"
"### User Data Location\n"
"\n"
"AMidiOrgan stores user data under:\n"
"\n"
"- `Documents/AMidiOrgan`\n"
"\n"
"Important subfolders:\n"
"\n"
"- `configs/` for `.cfg` files\n"
"- `panels/` for `.pnl` files\n"
"- `instruments/` for JSON instrument catalogs\n"
"- `configs/hotkeys.json` for keyboard shortcut bindings\n"
"\n"
"### What Each File Stores\n"
"\n"
"- `.cfg`\n"
"  - MIDI routing, group naming, split points, pass-through behavior, and related configuration\n"
"- `.pnl`\n"
"  - voice button assignments\n"
"  - button group details\n"
"  - presets\n"
"  - panel-level saved state such as manual rotary values\n"
"- `hotkeys.json`\n"
"  - customized keyboard shortcuts\n"
"\n"
"### Pairing and Save Behavior\n"
"\n"
"- Panels and configs are related: a panel stores the config name it expects.\n"
"- If you load a panel and config that do not match, the app can warn and let you abort or continue.\n"
"- While a config/panel mismatch is acknowledged, normal panel `Save` may remain disabled until the relationship is resolved.\n"
"- `Save As` can be used to write a new panel that matches the current config.\n"
"- If you change a sound module assignment inside a config that other panels depend on, saving that same config name may be blocked so older panels are not silently broken.\n"
"\n"
"### Practical Save Advice\n"
"\n"
"- Use `Save` regularly after meaningful panel edits.\n"
"- Use `Save As` before major changes so you keep a fallback version.\n"
"- After saving, reload once to confirm the expected state was written.\n"
"\n"
"## Window Move Tip\n"
"\n"
"- Click and drag in empty space on the top tab bar to move the app window.\n"
"- This preserves the slim title-bar layout while still letting you reposition the window.\n"
"\n"
"## MIDI Troubleshooting\n"
"\n"
"### No sound\n"
"\n"
"- Verify that the MIDI output device is connected and selected.\n"
"- Check the mute state and output channel on the active voice button group.\n"
"- Confirm that the selected module matches the actual sound source.\n"
"- Confirm that the intended voice button is active.\n"
"\n"
"### Notes not routing correctly\n"
"\n"
"- Check `Config` page MIDI In / Out channel mapping.\n"
"- Verify split note settings for solo groups.\n"
"- Confirm the intended config file is loaded.\n"
"\n"
"### Unexpected voice or effect\n"
"\n"
"- Confirm the active preset and active voice button.\n"
"- Re-open `Sounds` or `Effects` and verify the assigned values.\n"
"- If using custom hotkeys, confirm the current `hotkeys.json` matches what you expect.\n"
"\n"
"## Pre-Performance Checklist (2-3 Minutes)\n"
"\n"
"- Open each main tab once: `Start`, `Upper`, `Lower`, `Bass&Drums`, `Sounds`, `Effects`, `Config`, `Hotkeys`, `Help`.\n"
"- Verify MIDI devices are present and stable.\n"
"- Trigger notes on `Upper`, `Lower`, and `Bass&Drums`.\n"
"- Check mute states and voice button group volume levels.\n"
"- Recall at least one saved preset and confirm that the expected voices load.\n"
"- If you use custom hotkeys, test one tab shortcut and one preset shortcut.\n"
"- Save the current panel snapshot if you changed anything.\n"
"\n"
"## Contact Details\n"
"\n"
"- Anton Minnie, email: `a_minnie@hotmail.com`\n";

const char* help_md = (const char*) temp_binary_data_5;
}
